version: "3.9"

services:
  orchard-interview:
    image: orchard-interview
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
